// This file is auto-generated by Supabase CLI.
// Run: supabase gen types typescript --project-id <ID> > src/types/database.types.ts
// For now this is a placeholder — fill in after Supabase project is configured.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          username: string;
          full_name: string | null;
          avatar_url: string | null;
          institution_id: string | null;
          course_id: string | null;
          semester: number | null;
          reputation: number;
          plan: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          username: string;
          full_name?: string | null;
          avatar_url?: string | null;
          institution_id?: string | null;
          course_id?: string | null;
          semester?: number | null;
          reputation?: number;
          plan?: string;
        };
        Update: {
          username?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          institution_id?: string | null;
          course_id?: string | null;
          semester?: number | null;
          reputation?: number;
          plan?: string;
        };
      };
      institutions: {
        Row: {
          id: string;
          name: string;
          acronym: string | null;
          city: string | null;
          state: string | null;
          verified: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          acronym?: string | null;
          city?: string | null;
          state?: string | null;
          verified?: boolean;
        };
        Update: {
          name?: string;
          acronym?: string | null;
          city?: string | null;
          state?: string | null;
          verified?: boolean;
        };
      };
      courses: {
        Row: {
          id: string;
          institution_id: string;
          name: string;
          area: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          institution_id: string;
          name: string;
          area?: string | null;
        };
        Update: {
          institution_id?: string;
          name?: string;
          area?: string | null;
        };
      };
      subjects: {
        Row: {
          id: string;
          course_id: string;
          name: string;
          code: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          course_id: string;
          name: string;
          code?: string | null;
        };
        Update: {
          course_id?: string;
          name?: string;
          code?: string | null;
        };
      };
      documents: {
        Row: {
          id: string;
          uploader_id: string;
          subject_id: string;
          title: string;
          type: string;
          professor: string | null;
          semester: string | null;
          file_path: string;
          file_size: number | null;
          mime_type: string | null;
          page_count: number | null;
          view_count: number;
          download_count: number;
          score: number;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          uploader_id: string;
          subject_id: string;
          title: string;
          type: string;
          professor?: string | null;
          semester?: string | null;
          file_path: string;
          file_size?: number | null;
          mime_type?: string | null;
          page_count?: number | null;
          view_count?: number;
          download_count?: number;
          score?: number;
          status?: string;
        };
        Update: {
          title?: string;
          type?: string;
          professor?: string | null;
          semester?: string | null;
          status?: string;
          score?: number;
          view_count?: number;
          download_count?: number;
          page_count?: number | null;
        };
      };
      votes: {
        Row: {
          id: string;
          user_id: string;
          document_id: string;
          value: number;
          reason: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          document_id: string;
          value: number;
          reason?: string | null;
        };
        Update: {
          value?: number;
          reason?: string | null;
        };
      };
      downloads: {
        Row: {
          id: string;
          user_id: string;
          document_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          document_id: string;
        };
        Update: {
          user_id?: string;
          document_id?: string;
        };
      };
      reputation_events: {
        Row: {
          id: string;
          user_id: string;
          type: string;
          delta: number;
          document_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: string;
          delta: number;
          document_id?: string | null;
        };
        Update: {
          type?: string;
          delta?: number;
          document_id?: string | null;
        };
      };
    };
  };
}
